feat: expose safe tx eip712 structured data
gnosis/gnosis-py pull request #120
Opened 2021-11-03 09:09 UTC by banteg

Expose the EIP712 structured data of a SafeTx as `safe_tx_data` (extracted from `safe_tx_hash`).

This structure could be useful elsewhere, ranging from third-party signing to verification purposes.

My use case is passing it to Frame for signing.

2021-11-03 09:51 UTC, Uxio0 requested changes
Good PR! I'm also thinking on migrating to the newer library `eip712_structs` that I'm using for the Gnosis Protocol: https://github.com/gnosis/gnosis-py/blob/master/gnosis/protocol/order.py

2021-11-03 09:51 UTC, Uxio0 commented on gnosis/safe/safe_tx.py
> +    def safe_tx_data(self) -> Dict:
I think this name is misleading. What do you think renaming the function to `def eip712_structured_data(self)`?

2021-11-04 13:18 UTC, banteg commented
There is also a good library called [eip712](https://github.com/ApeWorX/eip712/blob/68f5ebbf8603dcd137251eed93ace2caaed09e2d/tests/test_messages.py#L56-L66), but I found a [name clash bug](https://github.com/ApeWorX/eip712/issues/9) in it when trying to implement the struct used here.

2021-11-04 13:23 UTC, Uxio0 approved these changes

2021-11-04 13:27 UTC, merged